#!/usr/bin/env bash
# Prepares the workflow runtime. Idempotent; safe to re-run.
#
# Dependencies install into ~/.cursor/workflows-runtime/deps so the user's repo
# never gains a package.json entry, a lockfile change, or a node_modules tree.
#
#   bootstrap.sh [project-dir]

set -euo pipefail

PROJECT_DIR="${1:-$PWD}"
RUNTIME_ROOT="$HOME/.cursor/workflows-runtime"
DEPS_DIR="$RUNTIME_ROOT/deps"
PLUGIN_SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SDK_VERSION="${WORKFLOW_SDK_VERSION:-latest}"
TSX_VERSION="${WORKFLOW_TSX_VERSION:-4}"

echo "==> runtime root: $RUNTIME_ROOT"
mkdir -p "$DEPS_DIR" "$RUNTIME_ROOT/runs"

if [ ! -f "$DEPS_DIR/package.json" ]; then
  cat >"$DEPS_DIR/package.json" <<'JSON'
{
  "name": "dynamic-workflows-deps",
  "private": true,
  "type": "module",
  "description": "Isolated dependencies for the dynamic-workflows runtime."
}
JSON
fi

if [ ! -x "$DEPS_DIR/node_modules/.bin/tsx" ] || [ ! -d "$DEPS_DIR/node_modules/@cursor/sdk" ]; then
  # typescript and @types/node are here so workflow authors can typecheck a
  # script before spending anything on it.
  echo "==> installing @cursor/sdk, tsx, and typescript (this happens once)"
  (cd "$DEPS_DIR" && npm install --silent --no-audit --no-fund \
    "@cursor/sdk@$SDK_VERSION" "tsx@$TSX_VERSION" typescript @types/node)
else
  echo "==> dependencies already present"
fi

# Type-only shim so generated workflow scripts get full editor types.
# Copied verbatim rather than re-exported from the plugin: a generated workflow
# must not contain a path back here, or it breaks when the plugin is moved,
# upgraded, or reinstalled somewhere else.
WORKFLOWS_DIR="$PROJECT_DIR/.cursor/workflows"
mkdir -p "$WORKFLOWS_DIR"
{
  echo "// Generated by the dynamic-workflows plugin. Do not edit."
  echo "// Type-only: nothing here is imported at runtime. Refresh with bootstrap.sh."
  cat "$PLUGIN_SKILL_DIR/runtime/public-types.ts"
} >"$WORKFLOWS_DIR/_runtime.ts"

echo "==> project workflows dir: $WORKFLOWS_DIR"

if [ -z "${CURSOR_API_KEY:-}" ]; then
  echo
  echo "!! CURSOR_API_KEY is not set."
  echo "   Workflow agents authenticate with it, and its usage is billed"
  echo "   separately from your IDE session."
  echo "   Mint one at https://cursor.com/dashboard/integrations then:"
  echo "     export CURSOR_API_KEY=\"cursor_...\""
  echo
else
  echo "==> CURSOR_API_KEY is set"
fi

echo "==> ready. Launch with: $PLUGIN_SKILL_DIR/wf run <script>"
